# Generated by Django 4.0.4 on 2022-07-30 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_bookingroom'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=50)),
                ('number_seat', models.IntegerField()),
                ('room_position', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='BookingStudyRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_code', models.CharField(max_length=20)),
                ('seat', models.IntegerField()),
                ('study_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.studyroom')),
            ],
        ),
    ]
