# Generated by Django 4.0.4 on 2022-07-30 11:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_studyroom_bookingstudyroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingstudyroom',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 7, 30, 11, 2, 30, 532050, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
