# Generated by Django 4.0.4 on 2022-08-03 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_bookingstudyroom_created_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reflect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_reflect', models.IntegerField()),
                ('danger', models.BooleanField(default=False)),
                ('note', models.TextField(max_length=255)),
                ('isSeenByAdmin', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.room')),
            ],
        ),
    ]
