# Generated by Django 4.0.4 on 2022-08-15 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingstudyroom',
            name='booking_date',
            field=models.DateField(null=True),
        ),
    ]
